-- VHDL module instantiation generated by SCUBA Diamond_1.3_Production (92)
-- Module  Version: 5.4
-- Thu Sep 22 11:23:40 2011

-- parameterized module component declaration
component fifo_512x64
    port (Data: in  std_logic_vector(71 downto 0); 
        WrClock: in  std_logic; RdClock: in  std_logic; 
        WrEn: in  std_logic; RdEn: in  std_logic; Reset: in  std_logic; 
        RPReset: in  std_logic; Q: out  std_logic_vector(71 downto 0); 
        Empty: out  std_logic; Full: out  std_logic);
end component;

-- parameterized module component instance
__ : fifo_512x64
    port map (Data(71 downto 0)=>__, WrClock=>__, RdClock=>__, WrEn=>__, 
        RdEn=>__, Reset=>__, RPReset=>__, Q(71 downto 0)=>__, Empty=>__, 
        Full=>__);
