-- VHDL module instantiation generated by SCUBA Diamond_1.3_Production (92)
-- Module  Version: 5.4
-- Mon Dec  5 18:27:25 2011

-- parameterized module component declaration
component fifo_1024x16x8
    port (Data: in  std_logic_vector(17 downto 0); 
        WrClock: in  std_logic; RdClock: in  std_logic; 
        WrEn: in  std_logic; RdEn: in  std_logic; Reset: in  std_logic; 
        RPReset: in  std_logic; Q: out  std_logic_vector(8 downto 0); 
        Empty: out  std_logic; Full: out  std_logic);
end component;

-- parameterized module component instance
__ : fifo_1024x16x8
    port map (Data(17 downto 0)=>__, WrClock=>__, RdClock=>__, WrEn=>__, 
        RdEn=>__, Reset=>__, RPReset=>__, Q(8 downto 0)=>__, Empty=>__, 
        Full=>__);
