-- VHDL module instantiation generated by SCUBA Diamond_1.3_Production (92)
-- Module  Version: 6.1
-- Mon Dec  5 22:40:38 2011

-- parameterized module component declaration
component statts_mem
    port (WrAddress: in  std_logic_vector(7 downto 0); 
        RdAddress: in  std_logic_vector(9 downto 0); 
        Data: in  std_logic_vector(31 downto 0); WE: in  std_logic; 
        RdClock: in  std_logic; RdClockEn: in  std_logic; 
        Reset: in  std_logic; WrClock: in  std_logic; 
        WrClockEn: in  std_logic; Q: out  std_logic_vector(7 downto 0));
end component;

-- parameterized module component instance
__ : statts_mem
    port map (WrAddress(7 downto 0)=>__, RdAddress(9 downto 0)=>__, Data(31 downto 0)=>__, 
        WE=>__, RdClock=>__, RdClockEn=>__, Reset=>__, WrClock=>__, 
        WrClockEn=>__, Q(7 downto 0)=>__);
